all_config:
 github_token: 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
 dingding:
   - enable: 1
   - webhook: https://oapi.dingtalk.com/robot/send?access_token=08d7136aceaa2db48027148fed2a8e200dfeb16bcdfb928cbce4a6479de2cba1
   - secretKey: SEC455bfbd94a98261d38b8e70d8f4e158d01c6dad3fe188eedff96d215b20558a9
   - app_name: dingding
 feishu:
   - enable: 0
   - webhook: xxx
   - app_name: feishu
 server:
   - enable: 0
   - sckey: 123123
   - app_name: server
 tgbot:
   - enable: 0
   - token: 123
   - group_id: 123
   - app_name: tgbot
 pushplus:
   - enable: 0
   - token: 123456
   - app_name: pushplus
 translate:
  - enable: 0
 black_user:
   - AlAIAL90